name: Deploy index.html to Yandex Object Storage

on:
  push:
    paths:
      - index.html  # запускается только если изменился index.html

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy index.html to Yandex Object Storage
        uses: nekitcorp/yandex-storage-website-action@v1
        with:
          accessKeyId: ${{ secrets.ACCESS_KEY_ID }}
          secretAccessKey: ${{ secrets.SECRET_ACCESS_KEY }}
          bucket: truruky.ru
          path: "/"               # загружаем в корень бакета
          clear: false            # не очищаем бакет перед загрузкой
          files: "index.html"     # указываем конкретный файл для загрузки

      #В ОРИГИНАЛЕ:
      # - name: Deploy
      #   uses: nekitcorp/yandex-storage-website-action@v1
      #   with:
      #     accessKeyId: ${{ secrets.ACCESS_KEY_ID }}
      #     secretAccessKey: ${{ secrets.SECRET_ACCESS_KEY }}
      #     bucket: ${{ secrets.BUCKET }}
      #     path: "./public"
      #     clear: true